### ISSUE TITLE
Package.json not working

### ISSUE THREAD

**Issue by jobobby04** [d-evelopers/HellsAngel#1]
ok so i got all the stuff downloaded, NodeJS 5.5.0 stable, HellsAngle github and all that.
Windows 10, japan local so i can play japanese games as well.
I did npm install at the game folder and it messes up when I run npm start
here is the log
http://pastebin.com/UVghsU12
also only using command prompt

**Comment by thingywhat** [comment]
Oh my, I wonder how long that has been a thing...

Anyway, there was *definitely* a problem in package.json, so I just committed a fix for that... Could you try again with the most recent commit and see if that works?

**Comment by jobobby04** [comment]
That fixed it, thank you.

**Comment by thingywhat** [comment]
Hey, no prob. Thanks for reporting the issue..!

Everything is still so early in development that I'm not sure how long it would have been until I looked at package.json.
